- name: Download github runer
  # become: false
  hosts: webservers
  tasks:
    - name: Create github action folder
      shell:
        cmd: cd ~/ && rm -rf actions-runner && mkdir -p actions-runner && cd actions-runner
    
    - name: Download the latest runner package
      shell:
        cmd: cd ~/actions-runner && curl -o actions-runner-linux-x64-2.317.0.tar.gz -L https://github.com/actions/runner/releases/download/v2.317.0/actions-runner-linux-x64-2.317.0.tar.gz

    - name: Extract the installer
      shell:
        cmd: cd ~/actions-runner && tar xzf ./actions-runner-linux-x64-2.317.0.tar.gz
