- name: Create another user as root user
  become: true
  become_user: root
  hosts: webservers
  tasks:
    - name: Create dainh user
      user:
        name: huudai09
        password: Huudai09
        groups: admin
