- name: Install github runer
  # become: false
  hosts: webservers
  vars:
    repo: https://github.com/hudy9x/namviek
    token: AWYMQK5FS3JPVZYSQR5QOR3FXPPOK
    runner_name: myrunner
  tasks:
    - name: Create the runner and start the configuration experience
      shell:
        cmd: cd ~/actions-runner && ./config.sh --unattended --url "{{ repo }}" --token "{{ token }}" --replace --name "{{ runner_name }}" --labels myvps

    - name: Last step, launch GithubRunner
      shell:
        cmd: cd ~/actions-runner && ./run.sh &
